#This File is used to store constant variables
#relted to the asteroids game

#Screen Settings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#steroid Constants
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 #SECONDS
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#Player Constants
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

#Bullet Constants
SHOT_RADIUS = 5
PLAYER_SHOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
